print ('Flask is used to communicate with the database and HTML files')
print ('WebAPI-1')
print ('WebAPI-2')
print ('WebAPI-3')
print ('WebAPI-4')
print('Route1')
print('Route2')
print('Route3')
print('Route4')
